In [ ]:
import pandas as pd
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [2]:
# Uploading the dataset
df = pd.read_csv('Mall_Customers.csv')

In [3]:
# Viewing the dataset
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
# Creating X
X = df[["Age" , "Annual Income (k$)" , "Spending Score (1-100)"]]

In [5]:
# Making the data standard
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [6]:
# Creating clustering model and column
kmeans = KMeans(n_clusters = 5)
df["cluster"] = kmeans.fit_predict(X_scaled)

In [7]:
# 3d plot to see the clusters
scatterplot_3d = px.scatter_3d(df , x = 'Age' , y = 'Annual Income (k$)' , z = 'Spending Score (1-100)' , color = 'cluster' , color_continuous_scale = 'RdYlGn')
scatterplot_3d.show()

In [8]:
# Creating PCA
pca = PCA(n_components = 2)
X_pca = pca.fit_transform(X_scaled)

In [9]:
# Splitting the data into 2 PCAs
df["PCA_1"] = X_pca[ : , 0]
df["PCA_2"] = X_pca[ : , 1]

In [10]:
# Viewing the new dataset
df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),cluster,PCA_1,PCA_2
0,1,Male,19,15,39,2,-0.615720,-1.763481
1,2,Male,21,15,81,0,-1.665793,-1.820747
2,3,Female,20,16,6,2,0.337862,-1.674799
3,4,Female,23,16,77,0,-1.456573,-1.772430
4,5,Female,31,17,40,2,-0.038465,-1.662740

In [11]:
# 2d plot to see the relationship of PCAs and clusters
pca_plot = px.scatter(df , x = 'PCA_1' , y = 'PCA_2', color = 'cluster' , color_continuous_scale = 'jet')
pca_plot.show()

In [12]:
# Determining the average of each column in every cluster
cluster_sum = df.groupby("cluster")[["Age" , "Annual Income (k$)" , "Spending Score (1-100)"]].mean()
cluster_sum

               Age  Annual Income (k$)  Spending Score (1-100)
cluster
0        25.272727           25.727273               79.363636
1        55.610169           48.864407               41.254237
2        27.957447           50.000000               44.638298
3        32.692308           86.538462               82.128205
4        40.727273           89.030303               16.939394